# Generated by Django 2.2.13 on 2020-08-11 16:54

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models

# Thirdparty Libraries
import books.models
import ckeditor.fields
import cuenta.libSobreEscribirImagen


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "other_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Other Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "other_last_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Other Last Name",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birh Date"),
                ),
                (
                    "ciudad_nacimiento",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "fecha_defuncion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Defunción"
                    ),
                ),
                (
                    "ciudad_defuncion",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "resumen_biografico",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Resumen Biográfico"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default="autor/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=books.models.image_path_autor,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "other_name_nombre",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Other Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "other_last_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Other Last Name",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birh Date"),
                ),
                (
                    "ciudad_nacimiento",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "fecha_defuncion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Defunción"
                    ),
                ),
                (
                    "ciudad_defuncion",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "resumen_biografico",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Resumen Biográfico"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        default="editor/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=books.models.image_path_editor,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor",
                "verbose_name_plural": "Editores",
                "ordering": ["name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Last Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Editorial",
                "verbose_name_plural": "Editoriales",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publicacion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_edicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Edición"
                    ),
                ),
                ("edicion", models.IntegerField(blank=True, null=True)),
                (
                    "fecha_publicacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Publicación"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "issn",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="ISSN"
                    ),
                ),
                ("numero", models.IntegerField(blank=True, null=True)),
                (
                    "titulo",
                    models.TextField(
                        blank=True, max_length=256, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "sub_titulo",
                    models.TextField(
                        blank=True, max_length=256, null=True, verbose_name="Sub Título"
                    ),
                ),
                (
                    "volumen",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Volumen"
                    ),
                ),
                (
                    "resumen",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Resumen"
                    ),
                ),
                ("cantidad_paginas", models.IntegerField(blank=True, null=True)),
                (
                    "portada",
                    models.ImageField(
                        blank=True,
                        default="portada/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=books.models.image_path_portada,
                    ),
                ),
                (
                    "autor",
                    models.ManyToManyField(
                        blank=True, related_name="autores", to="books.Autor"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="books.Categoria",
                    ),
                ),
                (
                    "editor",
                    models.ManyToManyField(
                        blank=True, related_name="editores", to="books.Editor"
                    ),
                ),
                (
                    "editorial",
                    models.ManyToManyField(
                        blank=True, related_name="editoriales", to="books.Editorial"
                    ),
                ),
            ],
            options={
                "verbose_name": "Publicacion",
                "verbose_name_plural": "Publicaciones",
                "ordering": ["titulo"],
            },
        ),
    ]
