# Generated by Django 2.2.17 on 2020-12-12 16:31

import books.models
import ckeditor.fields
import cuenta.libSobreEscribirImagen
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globales', '0011_auto_20201212_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BooksEditorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direction', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BooksPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('other_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Otro Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('other_last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Otro Apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ciudad de Nacimiento')),
                ('fecha_defuncion', models.DateField(blank=True, null=True, verbose_name='Fecha de Defunción')),
                ('ciudad_defuncion', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ciudad de Defunción')),
                ('resumen_biografico', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen Biográfico')),
                ('foto', models.ImageField(blank=True, default='books_persona/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=books.models.image_path_person)),
                ('is_autor', models.BooleanField(default=False)),
                ('is_editor', models.BooleanField(default=False)),
                ('pais_defuncion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_pais_dead', to='globales.Pais')),
                ('pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persona_pais_born', to='globales.Pais')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BooksPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_edicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Edición')),
                ('edition_number', models.IntegerField(blank=True, null=True, verbose_name='Edición N°')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=9, null=True, verbose_name='ISSN')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('titulo', models.TextField(blank=True, max_length=256, null=True, verbose_name='Título')),
                ('sub_titulo', models.TextField(blank=True, max_length=256, null=True, verbose_name='Sub Título')),
                ('volumen', models.CharField(blank=True, max_length=256, null=True, verbose_name='Volumen')),
                ('resumen', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen')),
                ('cantidad_paginas', models.IntegerField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, default='books_portada/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=books.models.image_path_portada, verbose_name='Portada')),
                ('pdf', models.ImageField(blank=True, default='books_pdf/default.png', max_length=255, null=True, storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(), upload_to=books.models.image_path_pdf, verbose_name='PDF')),
                ('autor', models.ManyToManyField(blank=True, related_name='autores', to='books.BooksPerson', verbose_name='Autor')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.BooksCategoria', verbose_name='Categoría')),
                ('editor', models.ManyToManyField(blank=True, related_name='editores', to='books.BooksPerson', verbose_name='Editor')),
                ('editorial', models.ManyToManyField(blank=True, related_name='editoriales', to='books.BooksEditorial', verbose_name='Editorial (es)')),
                ('pais_edicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_pais', to='globales.Pais', verbose_name='País de Edición')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['titulo'],
            },
        ),
    ]
