# Generated by Django 2.2.13 on 2020-12-07 14:38

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0010_auto_20201206_1848"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Categoria", new_name="BooksCategoria",),
        migrations.RenameModel(old_name="Editorial", new_name="BooksEditorial",),
        migrations.RenameModel(old_name="Person", new_name="BooksPerson",),
        migrations.RenameModel(old_name="Publicacion", new_name="BooksPublicacion",),
    ]
