# Generated by Django 2.2.13 on 2020-08-11 22:51

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="ciudad_defuncion",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ciudad Defunción"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="ciudad_nacimiento",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ciudad Nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="ciudad_defuncion",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ciudad Defunción"
            ),
        ),
        migrations.AlterField(
            model_name="editor",
            name="ciudad_nacimiento",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Ciudad Nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="editorial",
            name="direccion",
            field=models.TextField(blank=True, null=True, verbose_name="Dirección"),
        ),
    ]
