# Generated by Django 2.2.11 on 2020-03-28 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import globales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oeuconfig", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_estado_ine", models.CharField(max_length=2)),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={"db_table": "estado", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="Etnia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={"db_table": "etnia"},
        ),
        migrations.CreateModel(
            name="InstitucionMinisterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("siglas", models.CharField(max_length=50)),
                ("rif", models.CharField(max_length=45)),
                (
                    "dep_admin",
                    models.CharField(
                        choices=[("PÚBLICA", "PÚBLICA"), ("PRIVADA", "PRIVADA")],
                        max_length=7,
                    ),
                ),
                (
                    "tipo_institucion",
                    models.CharField(
                        choices=[
                            ("IEU", "INSTITUCIÓN DE EDUCACIÓN UNIVERSITARIA"),
                            ("ENTE ADSCRITO", "ENTE ADSCRITO"),
                            ("OTRO", "OTRO"),
                        ],
                        max_length=37,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ente Adscrito",
                "verbose_name_plural": "Entes Adscritos",
                "db_table": "institucion_ministerial",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_municipio_completo_ine", models.CharField(max_length=4)),
                (
                    "id_estado_ine",
                    models.CharField(max_length=2, verbose_name=globales.models.Estado),
                ),
                ("id_municipio_ine", models.CharField(max_length=2)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.Estado",
                    ),
                ),
            ],
            options={"db_table": "municipio", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_iso", models.CharField(blank=True, max_length=3, null=True)),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("nombre_iso", models.CharField(blank=True, max_length=255, null=True)),
                ("alfa2", models.CharField(blank=True, max_length=2, null=True)),
                ("alfa3", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={"db_table": "pais"},
        ),
        migrations.CreateModel(
            name="Parroquia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_parroquia_completo_ine", models.CharField(max_length=6)),
                ("id_municipio_completo_ine", models.CharField(max_length=4)),
                ("id_estado_ine", models.CharField(max_length=2)),
                ("id_municipio_ine", models.CharField(max_length=2)),
                ("id_parroquia_ine", models.CharField(max_length=2)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.Municipio",
                    ),
                ),
            ],
            options={"db_table": "parroquia", "ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="CorreoInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=255)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.InstitucionMinisterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo Institución",
                "verbose_name_plural": "Correos Institución",
                "db_table": "correo_institucion",
            },
        ),
    ]
