# Generated by Django 2.2.11 on 2020-03-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oeuconfig", "0001_initial"),
        ("globales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoridadInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=255)),
                ("telefono", models.EmailField(max_length=19)),
                ("celular", models.EmailField(max_length=19)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.InstitucionMinisterial",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Autoridad Institución",
                "verbose_name_plural": "Autoridades Institución",
                "db_table": "autoridad_institucion",
            },
        )
    ]
