# Generated by Django 2.2.11 on 2020-04-20 00:14

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0002_autoridadinstitucion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parroquia",
            options={"ordering": ["estado__nombre, municipio__nombre, nombre"]},
        ),
        migrations.AddField(
            model_name="parroquia",
            name="estado",
            field=models.ForeignKey(
                db_column="estado",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="globales.Estado",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parroquia",
            name="municipio",
            field=models.ForeignKey(
                db_column="municipio",
                on_delete=django.db.models.deletion.PROTECT,
                to="globales.Municipio",
            ),
        ),
    ]
