# Generated by Django 2.2.11 on 2020-04-20 00:22

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0003_auto_20200419_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipio",
            name="estado",
            field=models.ForeignKey(
                db_column="estado",
                on_delete=django.db.models.deletion.PROTECT,
                to="globales.Estado",
            ),
        ),
    ]
