# Generated by Django 2.2.11 on 2020-05-22 02:52

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0004_auto_20200419_2022"),
    ]

    operations = [
        migrations.AlterModelOptions(name="estado", options={"ordering": ["nombre"]},),
        migrations.AlterModelOptions(
            name="municipio", options={"ordering": ["estado__nombre", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="parroquia",
            options={"ordering": ["estado__nombre", "municipio__nombre", "nombre"]},
        ),
    ]
