# Generated by Django 2.2.11 on 2020-05-22 02:53

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0005_auto_20200521_2252"),
    ]

    operations = [
        migrations.DeleteModel(name="CorreoInstitucion",),
    ]
