# Generated by Django 2.2.11 on 2020-05-22 02:54

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0002_auto_20200409_2230"),
        ("globales", "0006_delete_correoinstitucion"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorreoInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=255)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.InstitucionMinisterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo Institución",
                "verbose_name_plural": "Correos Institución",
                "db_table": "correo_institucion",
            },
        ),
    ]
