# Generated by Django 2.2.13 on 2020-06-21 01:51

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0007_correoinstitucion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucionministerial",
            name="siglas",
            field=models.CharField(max_length=10),
        ),
    ]
