# Generated by Django 2.2.13 on 2020-06-21 22:03

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("globales", "0008_auto_20200620_2151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parroquia",
            name="estado",
            field=models.ForeignKey(
                db_column="estado_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="globales.Estado",
            ),
        ),
        migrations.AlterField(
            model_name="parroquia",
            name="municipio",
            field=models.ForeignKey(
                db_column="municipio_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="globales.Municipio",
            ),
        ),
    ]
