# Generated by Django 2.2.11 on 2020-03-28 16:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activacion",
            fields=[
                (
                    "cod_activacion",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("interpretacion", models.CharField(max_length=255)),
            ],
            options={"db_table": 'oeu"."activacion'},
        ),
        migrations.CreateModel(
            name="ActividadCultural",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Actividad Cultural",
                "verbose_name_plural": "Actividades Culturales",
                "db_table": 'oeu"."actividad_cultural',
            },
        ),
        migrations.CreateModel(
            name="AgrupacionCivica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Agrupación Civica",
                "verbose_name_plural": "Agrupaciones Civicas",
                "db_table": 'oeu"."agrupacion_civica',
            },
        ),
        migrations.CreateModel(
            name="AyudaEconomica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Ayuda Económica",
                "verbose_name_plural": "Ayudas Económicas",
                "db_table": 'oeu"."tipo_ayuda_economica',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Bitacora",
            fields=[
                ("id_bitacora", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_tabla", models.CharField(max_length=64)),
                ("datos_registro", models.TextField()),
                ("fecha_hora_registro", models.DateTimeField()),
            ],
            options={"db_table": 'oeu"."bitacora'},
        ),
        migrations.CreateModel(
            name="DependenciaAdministrativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Dependencia Administrativa",
                "verbose_name_plural": "Dependencias Administrativas",
                "db_table": 'oeu"."dependencia_administrativa',
            },
        ),
        migrations.CreateModel(
            name="DisciplinaDeportiva",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Disciplina Deportiva",
                "verbose_name_plural": "Disciplinas Deportivas",
                "db_table": 'oeu"."disciplina_deportiva',
            },
        ),
        migrations.CreateModel(
            name="InstanciaAdministrativa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("publicar", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Instancia Administrativa",
                "verbose_name_plural": "Instancias Administrativas",
                "db_table": 'oeu"."instancia_administrativa',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Modalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Régimen de Estudio",
                "verbose_name_plural": "Regímenes de Estudio",
                "db_table": 'oeu"."modalidad',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="OrganizacionEstudiantil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Organizacion Estudiantil",
                "verbose_name_plural": "Organizaciones Estudiantiles",
                "db_table": 'oeu"."organizacion_estudiantil',
            },
        ),
        migrations.CreateModel(
            name="RedSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
                "db_table": 'oeu"."red_social',
            },
        ),
        migrations.CreateModel(
            name="RequisitoIngreso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Requisito de Ingreso",
                "verbose_name_plural": "Requisitos de Ingreso",
                "db_table": 'oeu"."requisito_ingreso',
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "db_table": 'oeu"."servicio',
            },
        ),
        migrations.CreateModel(
            name="TipoCarrera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de Programa Académico",
                "verbose_name_plural": "Tipos de Programa Académico",
                "db_table": 'oeu"."tipo_carrera',
            },
        ),
        migrations.CreateModel(
            name="TipoLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo de localidad",
                "verbose_name_plural": "Tipos de localidad",
                "db_table": 'oeu"."tipo_localidad',
            },
        ),
        migrations.CreateModel(
            name="TipoSoporteFormalCambio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Tipo SFC",
                "verbose_name_plural": "Tipos SFC",
                "db_table": 'oeu"."tipo_sfc',
            },
        ),
        migrations.CreateModel(
            name="TipoTurnoDeEstudio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Turno de Estudio",
                "verbose_name_plural": "Turnos de Estudio",
                "db_table": 'oeu"."turno',
            },
        ),
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Título",
                "verbose_name_plural": "Títulos",
                "db_table": 'oeu"."titulo',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SoporteFormalCambio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=255)),
                (
                    "numero_gaceta",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("fecha_gaceta", models.DateField(blank=True, null=True)),
                (
                    "archivo_adjunto",
                    models.FileField(
                        blank=True, null=True, upload_to="archivo_adjunto_sfc/"
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "tipo_sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.TipoSoporteFormalCambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soporte Formal de Cambio",
                "verbose_name_plural": "Soportes Formales de Cambio",
                "db_table": 'oeu"."soporte_formal_cambio',
            },
        ),
    ]
