# Generated by Django 2.2.11 on 2020-04-10 02:30

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0003_auto_20200409_2230"),
        ("oeuconfig", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Modalidad", new_name="Periodicidad",),
        migrations.AlterModelTable(name="periodicidad", table='oeu"."periodicidad',),
    ]
