# Generated by Django 2.2.11 on 2020-06-13 18:34

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0002_auto_20200409_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titulo",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
