# Generated by Django 2.2.13 on 2020-06-19 04:15

# Django Libraries
from django.db import migrations

# Thirdparty Libraries
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0003_auto_20200613_1434"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadcultural",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agrupacioncivica",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ayudaeconomica",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dependenciaadministrativa",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disciplinadeportiva",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizacionestudiantil",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="periodicidad",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="redsocial",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipocarrera",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipolocalidad",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tiposoporteformalcambio",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipoturnodeestudio",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="titulo",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
