# Generated by Django 2.2.11 on 2020-03-28 16:07

import cuenta.libSobreEscribirImagen
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields
import oeu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("globales", "0001_initial"),
        ("oeuconfig", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaConocimiento",
            fields=[
                (
                    "id_area_conocimiento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombre_area_conocimiento",
                    models.CharField(
                        max_length=100, verbose_name="Área de Conocimiento"
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Área de Conocimiento",
                "verbose_name_plural": "Áreas de Conocimiento",
                "db_table": 'oeu"."area_conocimiento',
                "ordering": ["nombre_area_conocimiento"],
            },
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("mercado_ocupacional", models.TextField(blank=True, null=True)),
                ("prioritaria", models.BooleanField(default=False)),
                ("nombre_edit", models.CharField(max_length=255)),
                ("descripcion_edit", models.TextField()),
                ("mercado_ocupacional_edit", models.TextField()),
                ("prioritaria_edit", models.BooleanField(default=False)),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                (
                    "area_conocimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="AreaConocimiento2",
                        to="oeu.AreaConocimiento",
                    ),
                ),
                (
                    "area_conocimiento_edit",
                    models.ForeignKey(
                        db_column="area_conocimiento_edit",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.AreaConocimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa Académico",
                "verbose_name_plural": "Programas Académicos",
                "db_table": 'oeu"."carrera',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CineFCampoAmplio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_cine_f_campo_amplio", models.CharField(max_length=2)),
                ("descripcion_campo_amplio", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "CINE Campo Amplio",
                "verbose_name_plural": "CINE Campos Amplios",
                "db_table": 'oeu"."cine_campo_amplio',
            },
        ),
        migrations.CreateModel(
            name="GrupoCarrera",
            fields=[
                (
                    "id_grupo_carrera",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_grupo_carrera", models.CharField(max_length=255)),
            ],
            options={"db_table": 'oeu"."grupo_carrera'},
        ),
        migrations.CreateModel(
            name="GrupoRamaEducacion",
            fields=[
                (
                    "id_grupo_rama_educacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre_grupo_rama_educacion", models.CharField(max_length=255)),
            ],
            options={"db_table": 'oeu"."grupo_rama_educacion'},
        ),
        migrations.CreateModel(
            name="Ieu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="ieu_logo/default.png",
                        max_length=255,
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "fachada",
                    models.ImageField(
                        blank=True,
                        default="ieu_fachada/default.png",
                        max_length=255,
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "logo_edit",
                    models.ImageField(
                        blank=True,
                        default="ieu_logo/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=oeu.models.image_path_logo,
                    ),
                ),
                (
                    "fachada_edit",
                    models.ImageField(
                        blank=True,
                        default="ieu_fachada/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=oeu.models.image_path_fachada,
                    ),
                ),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        db_column="persona_editor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion_ministerial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="globales.InstitucionMinisterial",
                    ),
                ),
                (
                    "institucion_ministerial_edit",
                    models.ForeignKey(
                        blank=True,
                        db_column="institucion_ministerial_edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institucionedit",
                        to="globales.InstitucionMinisterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insitución de Educación Universitaria",
                "verbose_name_plural": "Instituciones de Educación Universitaria",
                "db_table": 'oeu"."ieu',
                "ordering": ["institucion_ministerial"],
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("web_site", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("centro_poblado", models.CharField(max_length=255)),
                ("punto", djgeojson.fields.PointField(blank=True, null=True)),
                ("poligonal", djgeojson.fields.PolygonField(blank=True, null=True)),
                (
                    "fachada",
                    models.ImageField(
                        blank=True,
                        default="localidad_fachada/default.png",
                        max_length=255,
                        null=True,
                        upload_to="",
                    ),
                ),
                ("nombre_edit", models.CharField(max_length=255)),
                ("web_site_edit", models.CharField(max_length=255)),
                ("direccion_edit", models.TextField()),
                ("centro_poblado_edit", models.CharField(max_length=255)),
                ("punto_edit", djgeojson.fields.PointField()),
                ("poligonal_edit", djgeojson.fields.PolygonField()),
                (
                    "fachada_edit",
                    models.ImageField(
                        blank=True,
                        default="localidad_fachada/default.png",
                        max_length=255,
                        null=True,
                        storage=cuenta.libSobreEscribirImagen.SobreEscribirImagen(),
                        upload_to=oeu.models.image_path_localidad,
                    ),
                ),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
                "db_table": 'oeu"."localidad',
                "ordering": [
                    "ieu__institucion_ministerial",
                    "tipo_localidad",
                    "nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="SubTipoInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("orden", models.SmallIntegerField()),
                (
                    "nombre_edit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("orden_edit", models.SmallIntegerField()),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        db_column="persona_editor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Tipo IEU",
                "verbose_name_plural": "Sub Tipos IEU",
                "db_table": 'oeu"."sub_tipo_ieu',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoEspecificoIeuRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_especifico_ieu_revisor'},
        ),
        migrations.CreateModel(
            name="TipoEspecificoIeuRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_especifico_ieu_revisor_edit'},
        ),
        migrations.CreateModel(
            name="TipoEspecificoIeuSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_especifico_ieu_sfc'},
        ),
        migrations.CreateModel(
            name="TipoInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.SmallIntegerField()),
                ("nombre_edit", models.CharField(max_length=100)),
                ("orden_edit", models.SmallIntegerField()),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(
                        blank=True, default="00000001", max_length=9, null=True
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        db_column="persona_editor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo IEU",
                "verbose_name_plural": "Tipos IEU",
                "db_table": 'oeu"."tipo_ieu',
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoInstitucionSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
                (
                    "tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.TipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_ieu_sfc'},
        ),
        migrations.CreateModel(
            name="TipoInstitucionRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.TipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_ieu_revisor_edit'},
        ),
        migrations.CreateModel(
            name="TipoInstitucionRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.TipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."tipo_ieu_revisor'},
        ),
        migrations.AddField(
            model_name="tipoinstitucion",
            name="revisor",
            field=models.ManyToManyField(
                related_name="revisores_tipo_publicados",
                through="oeu.TipoInstitucionRevisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tipoinstitucion",
            name="revisor_edit",
            field=models.ManyToManyField(
                related_name="revisores_tipo_editando",
                through="oeu.TipoInstitucionRevisorEdit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tipoinstitucion",
            name="sfc",
            field=models.ManyToManyField(
                through="oeu.TipoInstitucionSfc", to="oeuconfig.SoporteFormalCambio"
            ),
        ),
        migrations.CreateModel(
            name="TipoEspecificoInstitucion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("orden", models.SmallIntegerField(verbose_name="Orden")),
                (
                    "nombre_edit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("orden_edit", models.SmallIntegerField()),
                ("publicar", models.BooleanField(default=False)),
                (
                    "cod_activacion",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        db_column="persona_editor_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisor",
                    models.ManyToManyField(
                        related_name="revisores_tipo_especifico_publicados",
                        through="oeu.TipoEspecificoIeuRevisor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisor_edit",
                    models.ManyToManyField(
                        related_name="revisores_t_e_edit",
                        through="oeu.TipoEspecificoIeuRevisorEdit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sfc",
                    models.ManyToManyField(
                        through="oeu.TipoEspecificoIeuSfc",
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
                (
                    "sub_tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.SubTipoInstitucion",
                    ),
                ),
                (
                    "sub_tipo_ieu_edit",
                    models.ForeignKey(
                        blank=True,
                        db_column="sub_tipo_ieu_edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oeutipoieuespecifico",
                        to="oeu.SubTipoInstitucion",
                    ),
                ),
                (
                    "tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.TipoInstitucion",
                    ),
                ),
                (
                    "tipo_ieu_edit",
                    models.ForeignKey(
                        blank=True,
                        db_column="tipo_ieu_edit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tipo_ieu_espec",
                        to="oeu.TipoInstitucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo IEU Específico",
                "verbose_name_plural": "Tipos IEU Específicos",
                "db_table": 'oeu"."tipo_especifico_ieu',
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="tipoespecificoieusfc",
            name="tipo_especifico_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oeu.TipoEspecificoInstitucion",
            ),
        ),
        migrations.AddField(
            model_name="tipoespecificoieurevisoredit",
            name="tipo_especifico_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oeu.TipoEspecificoInstitucion",
            ),
        ),
        migrations.AddField(
            model_name="tipoespecificoieurevisor",
            name="tipo_especifico_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="oeu.TipoEspecificoInstitucion",
            ),
        ),
        migrations.CreateModel(
            name="TelefonoLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Teléfono Localidad",
                "verbose_name_plural": "Teléfonos Localidad",
                "db_table": 'oeu"."telefono_localidad',
            },
        ),
        migrations.CreateModel(
            name="SubTipoInstitucionSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
                (
                    "sub_tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.SubTipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."sub_tipo_ieu_sfc'},
        ),
        migrations.CreateModel(
            name="SubTipoInstitucionRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.SubTipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."sub_tipo_ieu_revisor_edit'},
        ),
        migrations.CreateModel(
            name="SubTipoInstitucionRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_tipo_ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oeu.SubTipoInstitucion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."sub_tipo_ieu_revisor'},
        ),
        migrations.AddField(
            model_name="subtipoinstitucion",
            name="revisor",
            field=models.ManyToManyField(
                related_name="revisores_sub_tipo_publicados",
                through="oeu.SubTipoInstitucionRevisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subtipoinstitucion",
            name="revisor_edit",
            field=models.ManyToManyField(
                related_name="revisores_sub_tipo_editados",
                through="oeu.SubTipoInstitucionRevisorEdit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subtipoinstitucion",
            name="sfc",
            field=models.ManyToManyField(
                through="oeu.SubTipoInstitucionSfc", to="oeuconfig.SoporteFormalCambio"
            ),
        ),
        migrations.AddField(
            model_name="subtipoinstitucion",
            name="tipo_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="oeu.TipoInstitucion"
            ),
        ),
        migrations.AddField(
            model_name="subtipoinstitucion",
            name="tipo_ieu_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="tipo_ieu_edit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oeutipoieu1",
                to="oeu.TipoInstitucion",
            ),
        ),
        migrations.CreateModel(
            name="SubAreaConocimiento",
            fields=[
                (
                    "id_sub_area_conocimiento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "nombre_subarea_conocimiento",
                    models.CharField(
                        db_column="nombre_area_conocimiento", max_length=255
                    ),
                ),
                (
                    "id_area_conocimiento",
                    models.ForeignKey(
                        db_column="id_area_conocimiento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="areaConocimiento4",
                        to="oeu.AreaConocimiento",
                        verbose_name="Área de conocimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Área de Conocimiento",
                "verbose_name_plural": "Sub Áreas de Conocimiento",
                "db_table": 'oeu"."sub_area_conocimiento',
                "ordering": ["nombre_subarea_conocimiento"],
            },
        ),
        migrations.CreateModel(
            name="RedSocialLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=255)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
                (
                    "red_social",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.RedSocial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
                "db_table": 'oeu"."red_social_localidad',
            },
        ),
        migrations.CreateModel(
            name="OrganizacionEstudiantilLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
                (
                    "organizacion_estudiantil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.OrganizacionEstudiantil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizacion Estudiantil",
                "verbose_name_plural": "Organizaciones Estudiantiles",
                "db_table": 'oeu"."organizacion_estudiantil_localidad',
            },
        ),
        migrations.CreateModel(
            name="LocalidadSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_sfc'},
        ),
        migrations.CreateModel(
            name="LocalidadServicio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.Servicio",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_servicios'},
        ),
        migrations.CreateModel(
            name="LocalidadRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_revisor_edit'},
        ),
        migrations.CreateModel(
            name="LocalidadRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_revisor'},
        ),
        migrations.CreateModel(
            name="LocalidadRequisitoIngreso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "requisito_ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.RequisitoIngreso",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_requisito_ingreso'},
        ),
        migrations.CreateModel(
            name="LocalidadRedSocial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enlace", models.CharField(max_length=255)),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "red_social",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.RedSocial",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_red_social'},
        ),
        migrations.CreateModel(
            name="LocalidadOrganizacionEstudiantil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
                (
                    "organizacion_estudiantil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.OrganizacionEstudiantil",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_organizacion_estudiantil'},
        ),
        migrations.CreateModel(
            name="LocalidadDisciplinaDeportiva",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disciplina_deportiva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.DisciplinaDeportiva",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_disciplina_deportiva'},
        ),
        migrations.CreateModel(
            name="LocalidadAyudaEconomica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ayuda_economica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.AyudaEconomica",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_ayuda_economica'},
        ),
        migrations.CreateModel(
            name="LocalidadAgrupacionCivica",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agrupacion_civica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.AgrupacionCivica",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_agrupacion_civica'},
        ),
        migrations.CreateModel(
            name="LocalidadActividadCultural",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actividad_cultural",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.ActividadCultural",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Localidad"
                    ),
                ),
            ],
            options={"db_table": 'oeu"."localidad_actividad_cultural'},
        ),
        migrations.AddField(
            model_name="localidad",
            name="actividad_cultural",
            field=models.ManyToManyField(
                through="oeu.LocalidadActividadCultural",
                to="oeuconfig.ActividadCultural",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="agrupacion_civica",
            field=models.ManyToManyField(
                through="oeu.LocalidadAgrupacionCivica", to="oeuconfig.AgrupacionCivica"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="ayuda_economica",
            field=models.ManyToManyField(
                through="oeu.LocalidadAyudaEconomica", to="oeuconfig.AyudaEconomica"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="disciplina_deportiva",
            field=models.ManyToManyField(
                through="oeu.LocalidadDisciplinaDeportiva",
                to="oeuconfig.DisciplinaDeportiva",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                db_column="persona_editor_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_estado_pub",
                to="globales.Estado",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="estado_edit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_estado_edit",
                to="globales.Estado",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="oeu.Ieu"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="ieu_edit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ieu",
                to="oeu.Ieu",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_municipio_pub",
                to="globales.Municipio",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="municipio_edit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_municipio_edit",
                to="globales.Municipio",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="organizacion_estudiantil",
            field=models.ManyToManyField(
                through="oeu.LocalidadOrganizacionEstudiantil",
                to="oeuconfig.OrganizacionEstudiantil",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="parroquia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_parroquia_pub",
                to="globales.Parroquia",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="parroquia_edit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oeu_parroquia_edit",
                to="globales.Parroquia",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="red_social",
            field=models.ManyToManyField(
                through="oeu.LocalidadRedSocial", to="oeuconfig.RedSocial"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="requisito_ingreso",
            field=models.ManyToManyField(
                through="oeu.LocalidadRequisitoIngreso", to="oeuconfig.RequisitoIngreso"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="revisor",
            field=models.ManyToManyField(
                related_name="revisor_local_publicado",
                through="oeu.LocalidadRevisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="revisor_edit",
            field=models.ManyToManyField(
                related_name="revisores_local_edit",
                through="oeu.LocalidadRevisorEdit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="servicio",
            field=models.ManyToManyField(
                through="oeu.LocalidadServicio", to="oeuconfig.Servicio"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="sfc",
            field=models.ManyToManyField(
                through="oeu.LocalidadSfc", to="oeuconfig.SoporteFormalCambio"
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="tipo_localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.TipoLocalidad",
            ),
        ),
        migrations.AddField(
            model_name="localidad",
            name="tipo_localidad_edit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipoLocalidad",
                to="oeuconfig.TipoLocalidad",
            ),
        ),
        migrations.CreateModel(
            name="IeuSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Ieu"
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."ieu_sfc'},
        ),
        migrations.CreateModel(
            name="IeuRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Ieu"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."ieu_revisor_edit'},
        ),
        migrations.CreateModel(
            name="IeuRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Ieu"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."ieu_revisor'},
        ),
        migrations.AddField(
            model_name="ieu",
            name="localidad_principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localidades",
                to="oeu.Localidad",
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="localidad_principal_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="localidad_principal_edit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="local_ppal_edi",
                to="oeu.Localidad",
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="revisor",
            field=models.ManyToManyField(
                related_name="revisor_ieu_publicado",
                through="oeu.IeuRevisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="revisor_edit",
            field=models.ManyToManyField(
                related_name="revisores_ieu_edit",
                through="oeu.IeuRevisorEdit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="sfc",
            field=models.ManyToManyField(
                through="oeu.IeuSfc", to="oeuconfig.SoporteFormalCambio"
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="sub_tipo_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="oeu.SubTipoInstitucion"
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="sub_tipo_ieu_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="sub_tipo_ieu_edit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sutipedi",
                to="oeu.SubTipoInstitucion",
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="tipo_especifico_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="oeu.TipoEspecificoInstitucion",
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="tipo_especifico_ieu_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="tipo_especifico_ieu_edit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oeutipoespecificoedit",
                to="oeu.TipoEspecificoInstitucion",
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="tipo_ieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="oeu.TipoInstitucion"
            ),
        ),
        migrations.AddField(
            model_name="ieu",
            name="tipo_ieu_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="tipo_ieu_edit",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tipoInstitucionEdit",
                to="oeu.TipoInstitucion",
            ),
        ),
        migrations.CreateModel(
            name="DisciplinaDeportivaLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "disciplina_deportiva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.DisciplinaDeportiva",
                    ),
                ),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina Deportiva",
                "verbose_name_plural": "Disciplinas Deportivas",
                "db_table": 'oeu"."disciplina_deportiva_localidad',
            },
        ),
        migrations.CreateModel(
            name="CorreoLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=255)),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo Localidad",
                "verbose_name_plural": "Correos Localidad",
                "db_table": 'oeu"."correo_localidad',
            },
        ),
        migrations.CreateModel(
            name="CineFCampoEspecifico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_cine_f_campo_especifico", models.CharField(max_length=3)),
                ("descripcion_campo_especifico", models.CharField(max_length=255)),
                (
                    "id_cine_f_campo_amplio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.CineFCampoAmplio",
                    ),
                ),
            ],
            options={
                "verbose_name": "CINE Campo Especifico",
                "verbose_name_plural": "CINE Campos Especificos",
                "db_table": 'oeu"."cine_campo_especifico',
            },
        ),
        migrations.CreateModel(
            name="CineFCampoDetallado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_cine_f_campo_detallado", models.CharField(max_length=4)),
                ("descripcion_campo_detallado", models.CharField(max_length=255)),
                (
                    "id_cine_f_campo_especifico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.CineFCampoEspecifico",
                    ),
                ),
            ],
            options={
                "verbose_name": "CINE Campo Detallado",
                "verbose_name_plural": "CINE Campos Detallados",
                "db_table": 'oeu"."cine_campo_detallado',
            },
        ),
        migrations.CreateModel(
            name="CarreraTitulo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracion", models.SmallIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Carrera"
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.Modalidad",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.Titulo",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_titulo'},
        ),
        migrations.CreateModel(
            name="CarreraSfc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera_pre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Carrera"
                    ),
                ),
                (
                    "sfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.SoporteFormalCambio",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_sfc'},
        ),
        migrations.CreateModel(
            name="CarreraRevisorEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera_pre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Carrera"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_revisor_edit'},
        ),
        migrations.CreateModel(
            name="CarreraRevisor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera_pre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Carrera"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_revisor'},
        ),
        migrations.CreateModel(
            name="CarreraGrupoRamaEducaion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Carrera"
                    ),
                ),
                (
                    "grupo_rama_educacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.GrupoRamaEducacion",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_grupo_rama_educaion'},
        ),
        migrations.CreateModel(
            name="CarreraGrupoCarrera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Carrera"
                    ),
                ),
                (
                    "grupo_carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeu.GrupoCarrera",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_grupo_carrera'},
        ),
        migrations.AddField(
            model_name="carrera",
            name="carrera_titulo",
            field=models.ManyToManyField(
                related_name="carrera_titulo",
                through="oeu.CarreraTitulo",
                to="oeuconfig.Titulo",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_amplio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoAmplio2",
                to="oeu.CineFCampoAmplio",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_amplio_edit",
            field=models.ForeignKey(
                db_column="cine_f_campo_amplio_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoAmplio3",
                to="oeu.CineFCampoAmplio",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_detallado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoDetallado2",
                to="oeu.CineFCampoDetallado",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_detallado_edit",
            field=models.ForeignKey(
                db_column="cine_f_campo_detallado_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoDetallado3",
                to="oeu.CineFCampoDetallado",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_especifico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoEspecifico2",
                to="oeu.CineFCampoEspecifico",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="cine_f_campo_especifico_edit",
            field=models.ForeignKey(
                db_column="cine_f_campo_especifico_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="CineFCampoEspecifico3",
                to="oeu.CineFCampoEspecifico",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                db_column="persona_editor_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="ieu_acreditadora_edit",
            field=models.ForeignKey(
                db_column="ieu_acreditadora_edit",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institucionAcreditadora",
                to="oeu.Ieu",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="institucion_acreditadora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeu.Ieu",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="localidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="localidad_edit",
            field=models.ForeignKey(
                db_column="localidad_edit",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="localidad_edit",
                to="oeu.Localidad",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="revisor",
            field=models.ManyToManyField(
                related_name="revisor_carrera_pre_publicado",
                through="oeu.CarreraRevisor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="revisor_edit",
            field=models.ManyToManyField(
                related_name="revisores_carrera_pre_edit",
                through="oeu.CarreraRevisorEdit",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="sfc",
            field=models.ManyToManyField(
                through="oeu.CarreraSfc", to="oeuconfig.SoporteFormalCambio"
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="sub_area_conocimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="SubAreaConocimiento2",
                to="oeu.SubAreaConocimiento",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="sub_area_conocimiento_edit",
            field=models.ForeignKey(
                db_column="sub_area_conocimiento_edit",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="SubAreaConocimiento3",
                to="oeu.SubAreaConocimiento",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="tipo_carrera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_carreras",
                to="oeuconfig.TipoCarrera",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="tipo_carrera_edit",
            field=models.ForeignKey(
                db_column="tipo_carrera_edit",
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.TipoCarrera",
            ),
        ),
        migrations.CreateModel(
            name="AyudaEconomicaLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "ayuda_economica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.AyudaEconomica",
                    ),
                ),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayuda Económica",
                "verbose_name_plural": "Ayudas Económicas",
                "db_table": 'oeu"."tipo_ayuda_economica_localidad',
            },
        ),
        migrations.CreateModel(
            name="AgrupacionCivicaLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "agrupacion_civica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.AgrupacionCivica",
                    ),
                ),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agrupación Civica",
                "verbose_name_plural": "Agrupaciones Civicas",
                "db_table": 'oeu"."agrupacion_civica_localidad',
            },
        ),
        migrations.CreateModel(
            name="ActividadCulturalLocalidad",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_telefono", models.CharField(max_length=19)),
                (
                    "id_actividad_cultural",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.ActividadCultural",
                    ),
                ),
                (
                    "instancia_administrativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.InstanciaAdministrativa",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="oeu.Localidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad Cultural",
                "verbose_name_plural": "Actividades Culturales",
                "db_table": 'oeu"."actividad_cultural_localidad',
            },
        ),
    ]
