# Generated by Django 2.2.11 on 2020-03-31 20:07

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carreratitulo", old_name="modalidad", new_name="periodicidad",
        ),
    ]
