# Generated by Django 2.2.11 on 2020-04-10 02:30

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0001_initial"),
        ("oeu", "0002_auto_20200331_1607"),
    ]

    operations = [
        migrations.RemoveField(model_name="carrera", name="carrera_titulo",),
        migrations.AddField(
            model_name="carrera",
            name="titulo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Titulo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrera",
            name="titulo_edit",
            field=models.ForeignKey(
                db_column="titulo_edit",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="titulo",
                to="oeuconfig.Titulo",
            ),
            preserve_default=False,
        ),
    ]
