# Generated by Django 2.2.11 on 2020-04-10 22:37

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0002_auto_20200409_2230"),
        ("oeu", "0003_auto_20200409_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrera",
            name="periodicidad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Periodicidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrera",
            name="periodicidad_edit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periodicidad",
                to="oeuconfig.Periodicidad",
            ),
            preserve_default=False,
        ),
    ]
