# Generated by Django 2.2.11 on 2020-04-10 22:39

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0004_auto_20200410_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="periodicidad",
            field=models.ForeignKey(
                db_column="periodicidad",
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Periodicidad",
            ),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="periodicidad_edit",
            field=models.ForeignKey(
                db_column="periodicidad_edit",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periodicidad",
                to="oeuconfig.Periodicidad",
            ),
        ),
    ]
