# Generated by Django 2.2.11 on 2020-04-10 23:47

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0006_auto_20200410_1909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="institucion_acreditadora",
            field=models.ForeignKey(
                blank=True,
                db_column="institucion_acreditadora",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeu.Ieu",
            ),
        ),
    ]
