# Generated by Django 2.2.11 on 2020-04-10 23:49

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0007_auto_20200410_1947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="ieu_acreditadora_edit",
            field=models.ForeignKey(
                db_column="institucion_acreditadora_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institucionAcreditadora",
                to="oeu.Ieu",
            ),
        ),
    ]
