# Generated by Django 2.2.11 on 2020-04-10 23:51

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0008_auto_20200410_1949"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrera",
            name="duracion",
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrera",
            name="duracion_edit",
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
