# Generated by Django 2.2.11 on 2020-04-15 03:03

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0011_auto_20200410_2123"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areaconocimiento",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Área de Conocimiento",
                "verbose_name_plural": "Áreas de Conocimiento",
            },
        ),
        migrations.AlterModelOptions(
            name="subareaconocimiento",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Sub Área de Conocimiento",
                "verbose_name_plural": "Sub Áreas de Conocimiento",
            },
        ),
        migrations.RenameField(
            model_name="areaconocimiento",
            old_name="nombre_area_conocimiento",
            new_name="nombre",
        ),
        migrations.RenameField(
            model_name="subareaconocimiento",
            old_name="id_area_conocimiento",
            new_name="area_conocimiento",
        ),
        migrations.RenameField(
            model_name="subareaconocimiento",
            old_name="nombre_subarea_conocimiento",
            new_name="nombre",
        ),
        migrations.AlterField(
            model_name="carrera",
            name="ieu_acreditadora_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="institucion_acreditadora_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institucionAcreditadora",
                to="oeu.Ieu",
            ),
        ),
    ]
