# Generated by Django 2.2.11 on 2020-04-15 03:03

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0012_auto_20200414_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subareaconocimiento",
            name="area_conocimiento",
            field=models.ForeignKey(
                db_column="area_conocimiento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="areaConocimiento4",
                to="oeu.AreaConocimiento",
                verbose_name="Área de conocimiento",
            ),
        ),
    ]
