# Generated by Django 2.2.11 on 2020-04-15 03:11

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0013_auto_20200414_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaconocimiento",
            name="id_area_conocimiento",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
    ]
