# Generated by Django 2.2.11 on 2020-04-15 03:18

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0014_auto_20200414_2311"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="areaconocimiento", name="id_area_conocimiento",
        ),
        migrations.AddField(
            model_name="areaconocimiento",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
