# Generated by Django 2.2.11 on 2020-04-15 03:19

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0015_auto_20200414_2318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subareaconocimiento",
            name="id_sub_area_conocimiento",
            field=models.AutoField(db_column="id", primary_key=True, serialize=False),
        ),
    ]
