# Generated by Django 2.2.11 on 2020-05-24 01:41

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0019_auto_20200429_2127"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ieu",
            options={
                "ordering": ["tipo_especifico_ieu", "institucion_ministerial__nombre"],
                "verbose_name": "Insitución de Educación Universitaria",
                "verbose_name_plural": "Instituciones de Educación Universitaria",
            },
        ),
        migrations.AlterModelOptions(
            name="localidad",
            options={
                "ordering": ["ieu__institucion_ministerial", "nombre"],
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidades",
            },
        ),
        migrations.RemoveField(model_name="ieu", name="sub_tipo_ieu",),
        migrations.RemoveField(model_name="ieu", name="tipo_ieu",),
    ]
