# Generated by Django 2.2.11 on 2020-05-25 23:11

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0020_auto_20200523_2141"),
    ]

    operations = [
        migrations.RemoveField(model_name="ieu", name="sub_tipo_ieu_edit",),
        migrations.RemoveField(model_name="ieu", name="tipo_ieu_edit",),
    ]
