# Generated by Django 2.2.11 on 2020-06-13 18:34

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models

# Thirdparty Libraries
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oeuconfig", "0003_auto_20200613_1434"),
        ("oeu", "0021_auto_20200525_1911"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrera",
            name="titula",
            field=models.ManyToManyField(
                related_name="titula",
                through="oeu.CarreraTitulo",
                to="oeuconfig.Titulo",
            ),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="descripcion_edit",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="mercado_ocupacional_edit",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name="CarreraTituloEdit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracion", models.SmallIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oeu.Carrera"
                    ),
                ),
                (
                    "periodicidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.Periodicidad",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="oeuconfig.Titulo",
                    ),
                ),
            ],
            options={"db_table": 'oeu"."carrera_titulo_edit'},
        ),
        migrations.AddField(
            model_name="carrera",
            name="titula_edit",
            field=models.ManyToManyField(
                related_name="titula_e",
                through="oeu.CarreraTituloEdit",
                to="oeuconfig.Titulo",
            ),
        ),
    ]
