# Generated by Django 2.2.13 on 2020-06-17 02:27

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0023_auto_20200616_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="duracion",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="duracion_edit",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="periodicidad_edit",
            field=models.ForeignKey(
                blank=True,
                db_column="periodicidad_edit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="periodicidad",
                to="oeuconfig.Periodicidad",
            ),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="prioritaria_edit",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
