# Generated by Django 2.2.13 on 2020-06-17 02:31

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0024_auto_20200616_2227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="periodicidad",
            field=models.ForeignKey(
                blank=True,
                db_column="periodicidad",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Periodicidad",
            ),
        ),
        migrations.AlterField(
            model_name="carrera",
            name="prioritaria_edit",
            field=models.BooleanField(default=False),
        ),
    ]
