# Generated by Django 2.2.13 on 2020-06-17 16:27

# Django Libraries
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0025_auto_20200616_2231"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carreratitulo", options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="carreratituloedit", options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="carreratitulo",
            name="periodicidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Periodicidad",
            ),
        ),
        migrations.AlterField(
            model_name="carreratituloedit",
            name="periodicidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oeuconfig.Periodicidad",
            ),
        ),
    ]
