# Generated by Django 2.2.13 on 2020-06-19 04:13

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0026_auto_20200617_1227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subareaconocimiento",
            name="nombre",
            field=models.CharField(db_column="nombre", max_length=255),
        ),
    ]
