# Generated by Django 2.2.13 on 2020-06-19 04:17

# Django Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0027_auto_20200619_0013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subareaconocimiento",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
