# Generated by Django 2.2.13 on 2020-06-20 15:39

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0029_auto_20200619_0017"),
    ]

    operations = [
        migrations.RemoveField(model_name="carreratitulo", name="periodicidad",),
        migrations.RemoveField(model_name="carreratituloedit", name="periodicidad",),
    ]
