# Generated by Django 2.2.13 on 2020-06-22 22:44

# Django Libraries
from django.db import migrations

# Thirdparty Libraries
import ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0030_auto_20200620_1139"),
    ]

    operations = [
        migrations.AddField(
            model_name="subareaconocimiento",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="areaconocimiento",
            name="descripcion",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
