# Generated by Django 2.2.13 on 2020-07-06 23:37

# Django Libraries
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oeu", "0031_auto_20200622_1844"),
    ]

    operations = [
        migrations.RemoveField(model_name="carrera", name="duracion",),
        migrations.RemoveField(model_name="carrera", name="duracion_edit",),
        migrations.RemoveField(model_name="carrera", name="titulo",),
        migrations.RemoveField(model_name="carrera", name="titulo_edit",),
    ]
