# Generated by Django 2.2.17 on 2020-12-12 15:19

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oeu', '0032_auto_20200706_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='poligonal_edit',
            field=djgeojson.fields.PolygonField(blank=True, null=True),
        ),
    ]
